/**
 * ROSIE AESTHETIC STUDIO - KEZELÉSEK ADATBÁZISA (V7)
 * Személyre szabott, prémium kezelések
 */

const TREATMENTS_DATA = [
  {
    id: "melytisztito-arckezeles",
    name: "Mélytisztító arckezelés",
    subtitle: "Tisztítás & bőrmegújítás",
    category: "cleansing",
    categoryName: "Tisztítás & Megújítás",
    badge: "Mélytisztítás",
    duration: "90–120 perc",
    price: 18500,
    priceFormatted: "18 500 Ft-tól",
    priceDetails: "18 500 Ft (Tini 90p) / 21 500 Ft (Teljes 120p)",
    isTop4: true,
    topRank: 1,
    image: "images/szepitke-melytisztito-arckezeles.webp",
    shortDesc: "Alapos, mégis kíméletes tisztítás a tiszta, friss és lélegző bőrért.",
    fullDesc: "Alapos pórustisztítás és bőrmegújítás. A bőr kíméletes felpuhítása után precíz manuális komedóeltávolítást végzünk, fertőtlenítéssel, pórusösszehúzó és bőrnyugtató ápolással kiegészítve a tiszta és kiegyensúlyozott bőrképért.",
    targetAudience: "Mitesszeres, eltömődött, tisztítást igénylő arcbőrre.",
    expectation: "Rövid állapotfelmérés, letisztítás, kíméletes gőzölés/puhítás, manuális tisztítás, pórusösszehúzás és nyugtató hidratálás.",
    effects: [
      "Eltömődött pórusok és mitesszerek kíméletes kitisztítása",
      "Faggyútermelés természetes egyensúlyának támogatása",
      "Pórusösszehúzás és megnyugtatott bőrfelszín",
      "Tiszta, friss, azonnal fellélegző bőrkép"
    ],
    steps: ["Bőrállapot felmérése", "Előkészítés és puhítás", "Kíméletes tisztítás", "Hatóanyagos mélyápolás", "Befejező ápolás & fényvédelem"]
  },
  {
    id: "melyhidralato-glow",
    name: "Mélyhidratáló Glow kezelés",
    subtitle: "Hidratálás & ragyogás",
    category: "glow",
    categoryName: "Hidratálás & Ragyogás",
    badge: "Hidratálás & Glow",
    duration: "60–90 perc",
    price: 18500,
    priceFormatted: "18 500 Ft-tól",
    priceDetails: "18 500 Ft (60p) / 21 500 Ft (90p masszázzsal)",
    isTop4: true,
    topRank: 2,
    image: "images/szepitke-melyhidralato-glow.webp",
    shortDesc: "Intenzív nedvességpótlás és természetes, életteli ragyogás fakó bőrre.",
    fullDesc: "Többszintű hialuronsavas és antioxidáns infúzió, amely feltölti a bőr nedvességraktárait, megszünteti a kellemetlen húzódást és visszaadja az arc üde, selymes fényét.",
    targetAudience: "Száraz, vízhiányos, fakó vagy stressznek kitett bőrre.",
    expectation: "Gyengéd hámlasztás, intenzív szérumos hatóanyagbevitel, hidratáló pakolás és relaxáló simítások.",
    effects: [
      "Mélyrétegű nedvességpótlás és vízmegkötés",
      "Feszülő, száraz bőrérzet azonnali megszűnése",
      "Természetes, egészséges 'glass-skin' ragyogás",
      "Bársonyos, puha és rugalmas bőrfelszín"
    ],
    steps: ["Kíméletes letisztítás", "Enzimes peeling", "Hialuronsavas szérumbevitel", "Hidratáló gélmaszk", "Záró krémápolás"]
  },
  {
    id: "anti-aging-feszesito",
    name: "Anti-aging feszesítő kezelés",
    subtitle: "Feszesítés & anti-aging",
    category: "antiaging",
    categoryName: "Feszesítés & Anti-Aging",
    badge: "Anti-Aging & Lifting",
    duration: "60–90 perc",
    price: 22500,
    priceFormatted: "22 500 Ft-tól",
    priceDetails: "22 500 Ft (60p) / 24 500 Ft (90p lifting masszázzsal)",
    isTop4: true,
    topRank: 3,
    image: "images/szepitke-anti-aging-feszesito.webp",
    shortDesc: "Célzott bőrápolás a feszesebb, tónusosabb és fiatalosabb megjelenésért.",
    fullDesc: "Biomimetikus peptidekkel, kollagénstimuláló hatóanyagokkal és feszesítő arcmasszázzsal támogatja a bőr rugalmasságát, lágyítja a finom vonalakat és tonizálja a kontúrokat.",
    targetAudience: "Feszességét vesztett, tónustalan vagy ráncprevencióra vágyó érett bőrre.",
    expectation: "Peptides hatóanyag-bevitel, kollagénszintézist serkentő ápolás és stimuláló lifting masszázs.",
    effects: [
      "Bőrfeszesség és arckontúrok tónusának javulása",
      "Finom mimikai vonalak és ráncok optikai lágyítása",
      "Kollagéntermelés természetes serkentése",
      "Tömör, rugalmas és kisimult arcbőr"
    ],
    steps: ["Bőrállapot elemzése", "Finom peeling", "Peptid koncentrátum felvitele", "Feszesítő arcmasszázs", "Lifting maszk & záróápolás"]
  },
  {
    id: "problemas-bor-kezeles",
    name: "Problémás bőr célzott kezelése",
    subtitle: "Problémás bőr",
    category: "problemas",
    categoryName: "Problémás Bőr",
    badge: "Kiegyensúlyozás",
    duration: "60–90 perc",
    price: 18500,
    priceFormatted: "18 500 Ft-tól",
    priceDetails: "18 500 Ft (60p) / 21 500 Ft (90p)",
    isTop4: true,
    topRank: 4,
    image: "images/szepitke-problemas-bor-kezeles.webp",
    shortDesc: "Mitesszeres, kombinált és gyulladásra hajlamos bőr egyéni igényeire szabva.",
    fullDesc: "Gyulladáscsökkentő, antibakteriális és faggyúszabályozó növényi hatóanyagokkal és szalicilsavval dolgozunk, támogatva a bőr természetes védekezőképességét a kiújuló gyulladások ellen.",
    targetAudience: "Kombinált, zsírosodó, gyulladásra vagy aknéra hajlamos arcbőrre.",
    expectation: "Alapos letisztítás, kíméletes fertőtlenítés, gyulladáscsökkentő szérumok és mattító-hidratáló pakolás.",
    effects: [
      "Gyulladások és pirosság látványos mérséklése",
      "Faggyútermelés kiegyensúlyozása felesleges szárítás nélkül",
      "Pórusok tisztaságának és finomságának helyreállítása",
      "Megnyugtatott, kiegyensúlyozott védőréteg"
    ],
    steps: ["Bőrállapot felmérése", "BHA/Enzimes előkészítés", "Célzott gyulladáscsökkentés", "Nyugtató agyag- vagy gélmaszk", "Kiegyensúlyozó záróápolás"]
  },
  {
    id: "erzekeny-bor-nyugtato",
    name: "Érzékeny bőr nyugtató rituálé",
    subtitle: "Érzékeny bőr",
    category: "sensitive",
    categoryName: "Érzékeny & Reaktív Bőr",
    badge: "Nyugtatás & Barrier",
    duration: "60–90 perc",
    price: 21500,
    priceFormatted: "21 500 Ft-tól",
    priceDetails: "21 500 Ft (60p) / 23 500 Ft (90p)",
    isTop4: false,
    image: "images/szepitke-erzekeny-bor-nyugtato.webp",
    shortDesc: "Kifejezetten irritált, reaktív vagy kipirosodásra hajlamos bőr kíméletes megnyugtatása.",
    fullDesc: "Gyengéd, érfalvédő és bőrbarrier-erősítő hatóanyagokkal (panthenol, centella, allantoin, ceramidok) csökkenti az égő, feszülő érzést és a bőrpírt.",
    targetAudience: "Kipirosodásra hajlamos, rozáceás jellegű, sérült barrierű vagy reaktív bőrre.",
    expectation: "Kíméletes, illatanyagmentes kezelés, hűsítő és nyugtató maszkok, védőréteget helyreállító krémek.",
    effects: [
      "Bőrpír és kellemetlen melegérzet enyhítése",
      "Érfalak és mikrokeringés kíméletes támogatása",
      "Bőr természetes védőrétegének megerősítése",
      "Komfortos, megnyugtatott és puha bőrérzet"
    ],
    steps: ["Kíméletes tejes lemosás", "Nyugtató növényi tonizálás", "Érfalvédő szérumbevitel", "Hűsítő gélmaszk", "Barrier-építő lipidkrém"]
  },
  {
    id: "tu-nelkuli-mezoterapia",
    name: "Tű nélküli mezoterápia",
    subtitle: "Gépi hatóanyagbevitel",
    category: "special",
    categoryName: "Gépi Kezelések",
    badge: "Elektroporáció",
    duration: "60 perc",
    price: 22000,
    priceFormatted: "22 000 Ft",
    priceDetails: "22 000 Ft / alkalom (Bérletben kedvezménnyel)",
    isTop4: false,
    image: "images/szepitke-tu-nelkuli-mezoterapia.webp",
    shortDesc: "Modern elektroporációs kezelés tűszúrás nélkül, maximális hatóanyag-bevitellel.",
    fullDesc: "Elektromágneses hullámok segítségével mikroméretű csatornákat nyitunk a sejtek falán, így a steril hatóanyagok (orvosi tisztaságú hialuron, peptidek, vitaminok) mélyen a sejtekhez jutnak.",
    targetAudience: "Azonnali, mélyreható hatóanyag-bevitelt és intenzív revitalizálást keresőknek.",
    expectation: "Fájdalommentes, kellemes zizegő érzet, látványos feltöltöttség azonnal a kezelés után.",
    effects: [
      "Koncentrált hatóanyagok eljuttatása a mélyebb rétegekbe",
      "Azonnali feszesség, tömörség és feltöltöttség",
      "Sejtek regenerációjának felgyorsítása",
      "Tartós hidratáltság és ragyogás"
    ],
    steps: ["Bőr előkészítése", "Steril mezokoktél kiválasztása", "Elektroporációs hatóanyagbevitel", "Nyugtató lezárás", "Fényvédelem"]
  },
  {
    id: "carboxy-therapy",
    name: "Carboxy Therapy megújító kezelés",
    subtitle: "Szén-dioxid terápia",
    category: "special",
    categoryName: "Gépi Kezelések",
    badge: "Bőrlégzés & Ragyogás",
    duration: "60 perc",
    price: 22000,
    priceFormatted: "22 000 Ft",
    priceDetails: "22 000 Ft / alkalom",
    isTop4: false,
    image: "images/szepitke-carboxy-therapy.webp",
    shortDesc: "Szén-dioxid-alapú kozmetikai eljárás a bőr oxigénellátásának és mikrokeringésének felpezsdítésére.",
    fullDesc: "A Bohr-effektus elvén működő kezelés során megnöveljük a bőr oxigénfelvevő képességét, serkentve az anyagcserét, a méregtelenítést és a kollagénszintézist.",
    targetAudience: "Fáradt, fakó, városi környezetben élő vagy regenerációra szoruló arcbőrre.",
    expectation: "Pezsgő, melegedő érzet a gél és maszk aktiválódásakor, utána tiszta és ragyogó bőrkép.",
    effects: [
      "Bőr oxigénellátásának és anyagcseréjének turbó fokozása",
      "Pórusok finomítása és tónusjavítás",
      "Méregtelenítés és ödémák csökkentése",
      "Üde, életteli és rózsás arcszín"
    ],
    steps: ["Letisztítás", "Carboxy gél és aktivátor felvitele", "Hatóidő (kb. 20 perc)", "Bőséges lemosás", "Nyugtató szérum és krém"]
  },
  {
    id: "hamupipoke-expressz",
    name: "Hamupipőke Express",
    subtitle: "Gyors felfrissülés",
    category: "glow",
    categoryName: "Hidratálás & Ragyogás",
    badge: "Azonnali Ragyogás",
    duration: "30 perc",
    price: 15000,
    priceFormatted: "15 000 Ft",
    priceDetails: "15 000 Ft (Esemény előtti gyors felkészítés)",
    isTop4: false,
    image: "images/szepitke-hamupipoke-expressz.webp",
    shortDesc: "Gyors bőrfelfrissítés esemény előtt, amikor rövid idő alatt szeretnél üde ragyogást.",
    fullDesc: "Kifejezetten fontos randi, fotózás vagy esemény előtt ajánlott expressz ápolás, amely feszesíti a pórusokat és tökéletesen sima alapot teremt a sminknek.",
    targetAudience: "Kevés idővel rendelkezőknek, események vagy fotózások előtti gyors ragyogásra.",
    expectation: "Gyors letisztítás, ragyogásfokozó ampulla és tápláló fátyolmaszk.",
    effects: [
      "Azonnali látható simaság és frissesség",
      "Fáradtság jeleinek eltüntetése",
      "Tökéletes, egyenletes sminkalap biztosítása"
    ],
    steps: ["Gyors letisztítás", "Expressz glow peeling", "Ragyogásfokozó koncentrátum", "Fényvédő és hidratáló lezárás"]
  },
  {
    id: "kombinalt-bor-kezeles",
    name: "Kombinált bőr kiegyensúlyozó kezelés",
    subtitle: "Zónánkénti ápolás",
    category: "problemas",
    categoryName: "Problémás Bőr",
    badge: "Kiegyensúlyozás",
    duration: "60–90 perc",
    price: 18500,
    priceFormatted: "18 500 Ft-tól",
    priceDetails: "18 500 Ft (60p) / 21 500 Ft (90p)",
    isTop4: false,
    image: "images/szepitke-kombinalt-bor-kezeles.webp",
    shortDesc: "Kiegyensúlyozó ápolás a zsírosabb T-zóna mattítására és a szárazabb orcák hidratálására.",
    fullDesc: "Multimaszking és differenciált hatóanyag-bevitel a kombinált bőr speciális kettősségének harmonizálására.",
    targetAudience: "T-zónában fénylő, orcákon feszülő vagy hámló kombinált bőrre.",
    expectation: "Zónánként alkalmazott hatóanyagok: mattító összetevők a homlok-orr-áll területére, mélyhidratálás az orcákra.",
    effects: [
      "Faggyútermelés normalizálása a T-zónában",
      "Orcák szárazságának és húzódásának megszűnése",
      "Egységes bőrtextúra és bársonyos tapintás"
    ],
    steps: ["Letisztítás", "Kettős peeling", "Zónánkénti szérumbevitel", "Multimaszk alkalmazása", "Kiegyensúlyozó emulzió"]
  }
];
